/*
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.
 */

 class Solution {
    public char findTheDifference(String s, String t) {
        int[] counts = new int[26]; 

        for (char ch : t.toCharArray()) 
        {
            counts[ch - 'a']++;
        }

        for (char ch : s.toCharArray()) 
        {
            counts[ch - 'a']--;
        }

        for (int i = 0; i < 26; i++) 
        {
            if (counts[i] > 0) 
            {
                return (char)('a' + i);
            }
        }

        return ' ';
    }
}